services:
  localstack:
    image: localstack/localstack:3.8.1
    restart: always
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
  postgres:
    image: postgres:16.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.2.6-alpine
    restart: always
    ports:
      - 6379:6379
