version: "3.9"
services:
  memcached:
    image: memcached:1.6.6-alpine
    restart: always
    ports:
      - "11211:11211"
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - "6379:6379"
