version: "3.9"
services:
  localstack:
    image: localstack/localstack
    restart: always
    ports:
      - "4566:4566"
      - "4571:4571"
      - "5678:5678"
      - "8080:8080"
  memcached:
    image: memcached:1.6.10-alpine
    restart: always
    ports:
      - "11211:11211"
  postgres:
    image: postgres:13.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - "6379:6379"
